#-------------------------------------------------
#
# Project created by QtCreator 2020-11-09T15:03:01
#
#-------------------------------------------------

QT       += core gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TARGET = QSrcAnalysis
TEMPLATE = app

# The following define makes your compiler emit warnings if you use
# any feature of Qt which has been marked as deprecated (the exact warnings
# depend on your compiler). Please consult the documentation of the
# deprecated API in order to know how to port your code away from it.
DEFINES += QT_DEPRECATED_WARNINGS

# You can also make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0


SOURCES += \
    CopidQt/Widget/qaction.cpp \
    CopidQt/Widget/qactiongroup.cpp \
    CopidQt/Widget/qapplication.cpp \
    CopidQt/Widget/qboxlayout.cpp \
    CopidQt/Widget/qdesktopwidget.cpp \
    CopidQt/Widget/qformlayout.cpp \
    CopidQt/Widget/qgesture.cpp \
    CopidQt/Widget/qgesturemanager.cpp \
    CopidQt/Widget/qgesturerecognizer.cpp \
    CopidQt/Widget/qgridlayout.cpp \
    CopidQt/Widget/qlayout.cpp \
    CopidQt/Widget/qlayoutengine.cpp \
    CopidQt/Widget/qlayoutitem.cpp \
    CopidQt/Widget/qmacgesturerecognizer.cpp \
    CopidQt/Widget/qopenglwidget.cpp \
    CopidQt/Widget/qshortcut.cpp \
    CopidQt/Widget/qsizepolicy.cpp \
    CopidQt/Widget/qstackedlayout.cpp \
    CopidQt/Widget/qstandardgestures.cpp \
    CopidQt/Widget/qtestsupport_widgets.cpp \
    CopidQt/Widget/qtooltip.cpp \
    CopidQt/Widget/qwhatsthis.cpp \
    CopidQt/Widget/qwidget.cpp \
    CopidQt/Widget/qwidgetaction.cpp \
    CopidQt/Widget/qwidgetbackingstore.cpp \
    CopidQt/Widget/qwidgetsvariant.cpp \
    CopidQt/Widget/qwidgetwindow.cpp \
    CopidQt/Widget/qwindowcontainer.cpp \
    CopidQt/gui/kernel/qclipboard.cpp \
    CopidQt/gui/kernel/qcursor.cpp \
    CopidQt/gui/kernel/qdnd.cpp \
    CopidQt/gui/kernel/qdrag.cpp \
    CopidQt/gui/kernel/qevent.cpp \
    CopidQt/gui/kernel/qgenericplugin.cpp \
    CopidQt/gui/kernel/qgenericpluginfactory.cpp \
    CopidQt/gui/kernel/qguiapplication.cpp \
    CopidQt/gui/kernel/qguivariant.cpp \
    CopidQt/gui/kernel/qhighdpiscaling.cpp \
    CopidQt/gui/kernel/qinputdevicemanager.cpp \
    CopidQt/gui/kernel/qinputmethod.cpp \
    CopidQt/gui/kernel/qinternalmimedata.cpp \
    CopidQt/gui/kernel/qkeymapper.cpp \
    CopidQt/gui/kernel/qkeysequence.cpp \
    CopidQt/gui/kernel/qoffscreensurface.cpp \
    CopidQt/gui/kernel/qopenglcontext.cpp \
    CopidQt/gui/kernel/qopenglwindow.cpp \
    CopidQt/gui/kernel/qpaintdevicewindow.cpp \
    CopidQt/gui/kernel/qpalette.cpp \
    CopidQt/gui/kernel/qpixelformat.cpp \
    CopidQt/gui/kernel/qplatformclipboard.cpp \
    CopidQt/gui/kernel/qplatformcursor.cpp \
    CopidQt/gui/kernel/qplatformdialoghelper.cpp \
    CopidQt/gui/kernel/qplatformdrag.cpp \
    CopidQt/gui/kernel/qplatformgraphicsbuffer.cpp \
    CopidQt/gui/kernel/qplatformgraphicsbufferhelper.cpp \
    CopidQt/gui/kernel/qplatforminputcontext.cpp \
    CopidQt/gui/kernel/qplatforminputcontextfactory.cpp \
    CopidQt/gui/kernel/qplatforminputcontextplugin.cpp \
    CopidQt/gui/kernel/qplatformintegration.cpp \
    CopidQt/gui/kernel/qplatformintegrationfactory.cpp \
    CopidQt/gui/kernel/qplatformintegrationplugin.cpp \
    CopidQt/gui/kernel/qplatformmenu.cpp \
    CopidQt/gui/kernel/qplatformnativeinterface.cpp \
    CopidQt/gui/kernel/qplatformoffscreensurface.cpp \
    CopidQt/gui/kernel/qplatformopenglcontext.cpp \
    CopidQt/gui/kernel/qplatformscreen.cpp \
    CopidQt/gui/kernel/qplatformservices.cpp \
    CopidQt/gui/kernel/qplatformsessionmanager.cpp \
    CopidQt/gui/kernel/qplatformsharedgraphicscache.cpp \
    CopidQt/gui/kernel/qplatformsurface.cpp \
    CopidQt/gui/kernel/qplatformsystemtrayicon.cpp \
    CopidQt/gui/kernel/qplatformtheme.cpp \
    CopidQt/gui/kernel/qplatformthemefactory.cpp \
    CopidQt/gui/kernel/qplatformthemeplugin.cpp \
    CopidQt/gui/kernel/qplatformwindow.cpp \
    CopidQt/gui/kernel/qrasterwindow.cpp \
    CopidQt/gui/kernel/qscreen.cpp \
    CopidQt/gui/kernel/qsessionmanager.cpp \
    CopidQt/gui/kernel/qshapedpixmapdndwindow.cpp \
    CopidQt/gui/kernel/qshortcutmap.cpp \
    CopidQt/gui/kernel/qsimpledrag.cpp \
    CopidQt/gui/kernel/qstylehints.cpp \
    CopidQt/gui/kernel/qsurface.cpp \
    CopidQt/gui/kernel/qsurfaceformat.cpp \
    CopidQt/gui/kernel/qtestsupport_gui.cpp \
    CopidQt/gui/kernel/qtouchdevice.cpp \
    CopidQt/gui/kernel/qwindow.cpp \
    CopidQt/gui/kernel/qwindowsysteminterface.cpp \
        main.cpp \
        mainwindow.cpp \
    ../../Work/CopidQt/qcoreapplication.cpp \
    ../../Work/CopidQt/qmetaobject.cpp \
    ../../Work/CopidQt/qobject.cpp \
    ../../Work/CopidQt/qpoint.cpp \
    ../../Work/CopidQt/qpointer.cpp \
    ../../Work/CopidQt/qthread.cpp \
    ../../Work/CopidQt/qvariant.cpp \
    ../../Work/CopidQt/qwidget.cpp \
    CopidQt/implement/qcoreapplication.cpp \
    CopidQt/implement/qmetaobject.cpp \
    CopidQt/implement/qobject.cpp \
    CopidQt/implement/qpoint.cpp \
    CopidQt/implement/qpointer.cpp \
    CopidQt/implement/qthread.cpp \
    CopidQt/implement/qvariant.cpp \
    CopidQt/implement/qwidget.cpp \
    main.cpp \
    mainwindow.cpp \
    CopidQt/implement/qcoreapplication.cpp \
    CopidQt/implement/qmetaobject.cpp \
    CopidQt/implement/qobject.cpp \
    CopidQt/implement/qpoint.cpp \
    CopidQt/implement/qpointer.cpp \
    CopidQt/implement/qthread.cpp \
    CopidQt/implement/qvariant.cpp \
    CopidQt/implement/qwidget.cpp \
    main.cpp \
    mainwindow.cpp \
    CopidQt/implement/qtimer.cpp \
    CopidQt/implement/qabstracteventdispatcher.cpp \
    CopidQt/implement/qabstractnativeeventfilter.cpp \
    CopidQt/implement/qbasictimer.cpp \
    CopidQt/implement/qcfsocketnotifier.cpp \
    CopidQt/implement/qcore_mac.cpp \
    CopidQt/implement/qcore_unix.cpp \
    CopidQt/implement/qcoreapplication.cpp \
    CopidQt/implement/qcoreapplication_mac.cpp \
    CopidQt/implement/qcoreapplication_win.cpp \
    CopidQt/implement/qcoreevent.cpp \
    CopidQt/implement/qcoreglobaldata.cpp \
    CopidQt/implement/qdeadlinetimer.cpp \
    CopidQt/implement/qelapsedtimer.cpp \
    CopidQt/implement/qelapsedtimer_generic.cpp \
    CopidQt/implement/qelapsedtimer_mac.cpp \
    CopidQt/implement/qelapsedtimer_unix.cpp \
    CopidQt/implement/qelapsedtimer_win.cpp \
    CopidQt/implement/qeventdispatcher_glib.cpp \
    CopidQt/implement/qeventdispatcher_unix.cpp \
    CopidQt/implement/qeventdispatcher_win.cpp \
    CopidQt/implement/qeventdispatcher_winrt.cpp \
    CopidQt/implement/qeventloop.cpp \
    CopidQt/implement/qfunctions_nacl.cpp \
    CopidQt/implement/qfunctions_vxworks.cpp \
    CopidQt/implement/qfunctions_winrt.cpp \
    CopidQt/implement/qjni.cpp \
    CopidQt/implement/qjnihelpers.cpp \
    CopidQt/implement/qjnionload.cpp \
    CopidQt/implement/qmath.cpp \
    CopidQt/implement/qmetaobject.cpp \
    CopidQt/implement/qmetaobjectbuilder.cpp \
    CopidQt/implement/qmetatype.cpp \
    CopidQt/implement/qmimedata.cpp \
    CopidQt/implement/qobject.cpp \
    CopidQt/implement/qobjectcleanuphandler.cpp \
    CopidQt/implement/qpoint.cpp \
    CopidQt/implement/qpointer.cpp \
    CopidQt/implement/qpoll.cpp \
    CopidQt/implement/qppsattribute.cpp \
    CopidQt/implement/qppsobject.cpp \
    CopidQt/implement/qsharedmemory.cpp \
    CopidQt/implement/qsharedmemory_android.cpp \
    CopidQt/implement/qsharedmemory_posix.cpp \
    CopidQt/implement/qsharedmemory_systemv.cpp \
    CopidQt/implement/qsharedmemory_unix.cpp \
    CopidQt/implement/qsharedmemory_win.cpp \
    CopidQt/implement/qsignalmapper.cpp \
    CopidQt/implement/qsocketnotifier.cpp \
    CopidQt/implement/qsystemerror.cpp \
    CopidQt/implement/qsystemsemaphore.cpp \
    CopidQt/implement/qsystemsemaphore_android.cpp \
    CopidQt/implement/qsystemsemaphore_posix.cpp \
    CopidQt/implement/qsystemsemaphore_systemv.cpp \
    CopidQt/implement/qsystemsemaphore_unix.cpp \
    CopidQt/implement/qsystemsemaphore_win.cpp \
    CopidQt/implement/qtcore_eval.cpp \
    CopidQt/implement/qthread.cpp \
    CopidQt/implement/qtimer.cpp \
    CopidQt/implement/qtimerinfo_unix.cpp \
    CopidQt/implement/qtranslator.cpp \
    CopidQt/implement/qvariant.cpp \
    CopidQt/implement/qwidget.cpp \
    CopidQt/implement/qwineventnotifier.cpp \
    main.cpp \
    mainwindow.cpp \
    CopidQt/Widget/qabstractbutton.cpp \
    CopidQt/Widget/qabstractscrollarea.cpp \
    CopidQt/Widget/qabstractslider.cpp \
    CopidQt/Widget/qabstractspinbox.cpp \
    CopidQt/Widget/qaction.cpp \
    CopidQt/Widget/qactiongroup.cpp \
    CopidQt/Widget/qapplication.cpp \
    CopidQt/Widget/qboxlayout.cpp \
    CopidQt/Widget/qbuttongroup.cpp \
    CopidQt/Widget/qcalendarwidget.cpp \
    CopidQt/Widget/qcheckbox.cpp \
    CopidQt/Widget/qcombobox.cpp \
    CopidQt/Widget/qcommandlinkbutton.cpp \
    CopidQt/Widget/qdatetimeedit.cpp \
    CopidQt/Widget/qdesktopwidget.cpp \
    CopidQt/Widget/qdial.cpp \
    CopidQt/Widget/qdialogbuttonbox.cpp \
    CopidQt/Widget/qdockarealayout.cpp \
    CopidQt/Widget/qdockwidget.cpp \
    CopidQt/Widget/qeffects.cpp \
    CopidQt/Widget/qfocusframe.cpp \
    CopidQt/Widget/qfontcombobox.cpp \
    CopidQt/Widget/qformlayout.cpp \
    CopidQt/Widget/qframe.cpp \
    CopidQt/Widget/qgesture.cpp \
    CopidQt/Widget/qgesturemanager.cpp \
    CopidQt/Widget/qgesturerecognizer.cpp \
    CopidQt/Widget/qgridlayout.cpp \
    CopidQt/Widget/qgroupbox.cpp \
    CopidQt/Widget/qkeysequenceedit.cpp \
    CopidQt/Widget/qlabel.cpp \
    CopidQt/Widget/qlayout.cpp \
    CopidQt/Widget/qlayoutengine.cpp \
    CopidQt/Widget/qlayoutitem.cpp \
    CopidQt/Widget/qlcdnumber.cpp \
    CopidQt/Widget/qlineedit.cpp \
    CopidQt/Widget/qlineedit_p.cpp \
    CopidQt/Widget/qmacgesturerecognizer.cpp \
    CopidQt/Widget/qmainwindow.cpp \
    CopidQt/Widget/qmainwindowlayout.cpp \
    CopidQt/Widget/qmdiarea.cpp \
    CopidQt/Widget/qmdisubwindow.cpp \
    CopidQt/Widget/qmenu.cpp \
    CopidQt/Widget/qmenubar.cpp \
    CopidQt/Widget/qopenglwidget.cpp \
    CopidQt/Widget/qplaintextedit.cpp \
    CopidQt/Widget/qprogressbar.cpp \
    CopidQt/Widget/qpushbutton.cpp \
    CopidQt/Widget/qradiobutton.cpp \
    CopidQt/Widget/qrubberband.cpp \
    CopidQt/Widget/qscrollarea.cpp \
    CopidQt/Widget/qscrollbar.cpp \
    CopidQt/Widget/qshortcut.cpp \
    CopidQt/Widget/qsizegrip.cpp \
    CopidQt/Widget/qsizepolicy.cpp \
    CopidQt/Widget/qslider.cpp \
    CopidQt/Widget/qspinbox.cpp \
    CopidQt/Widget/qsplashscreen.cpp \
    CopidQt/Widget/qsplitter.cpp \
    CopidQt/Widget/qstackedlayout.cpp \
    CopidQt/Widget/qstackedwidget.cpp \
    CopidQt/Widget/qstandardgestures.cpp \
    CopidQt/Widget/qstatusbar.cpp \
    CopidQt/Widget/qtabbar.cpp \
    CopidQt/Widget/qtabwidget.cpp \
    CopidQt/Widget/qtestsupport_widgets.cpp \
    CopidQt/Widget/qtextbrowser.cpp \
    CopidQt/Widget/qtextedit.cpp \
    CopidQt/Widget/qtoolbar.cpp \
    CopidQt/Widget/qtoolbararealayout.cpp \
    CopidQt/Widget/qtoolbarextension.cpp \
    CopidQt/Widget/qtoolbarlayout.cpp \
    CopidQt/Widget/qtoolbarseparator.cpp \
    CopidQt/Widget/qtoolbox.cpp \
    CopidQt/Widget/qtoolbutton.cpp \
    CopidQt/Widget/qtooltip.cpp \
    CopidQt/Widget/qwhatsthis.cpp \
    CopidQt/Widget/qwidget.cpp \
    CopidQt/Widget/qwidgetaction.cpp \
    CopidQt/Widget/qwidgetanimator.cpp \
    CopidQt/Widget/qwidgetbackingstore.cpp \
    CopidQt/Widget/qwidgetlinecontrol.cpp \
    CopidQt/Widget/qwidgetresizehandler.cpp \
    CopidQt/Widget/qwidgetsvariant.cpp \
    CopidQt/Widget/qwidgettextcontrol.cpp \
    CopidQt/Widget/qwidgetwindow.cpp \
    CopidQt/Widget/qwindowcontainer.cpp \
    network/access/http2/bitstreams.cpp \
    network/access/http2/hpack.cpp \
    network/access/http2/hpacktable.cpp \
    network/access/http2/http2frames.cpp \
    network/access/http2/http2protocol.cpp \
    network/access/http2/http2streams.cpp \
    network/access/http2/huffman.cpp \
    network/access/qabstractnetworkcache.cpp \
    network/access/qabstractprotocolhandler.cpp \
    network/access/qftp.cpp \
    network/access/qhsts.cpp \
    network/access/qhstspolicy.cpp \
    network/access/qhstsstore.cpp \
    network/access/qhttp2protocolhandler.cpp \
    network/access/qhttpmultipart.cpp \
    network/access/qhttpnetworkconnection.cpp \
    network/access/qhttpnetworkconnectionchannel.cpp \
    network/access/qhttpnetworkheader.cpp \
    network/access/qhttpnetworkreply.cpp \
    network/access/qhttpnetworkrequest.cpp \
    network/access/qhttpprotocolhandler.cpp \
    network/access/qhttpthreaddelegate.cpp \
    network/access/qnetworkaccessauthenticationmanager.cpp \
    network/access/qnetworkaccessbackend.cpp \
    network/access/qnetworkaccesscache.cpp \
    network/access/qnetworkaccesscachebackend.cpp \
    network/access/qnetworkaccessdebugpipebackend.cpp \
    network/access/qnetworkaccessfilebackend.cpp \
    network/access/qnetworkaccessftpbackend.cpp \
    network/access/qnetworkaccessmanager.cpp \
    network/access/qnetworkcookie.cpp \
    network/access/qnetworkcookiejar.cpp \
    network/access/qnetworkdiskcache.cpp \
    network/access/qnetworkfile.cpp \
    network/access/qnetworkreply.cpp \
    network/access/qnetworkreplydataimpl.cpp \
    network/access/qnetworkreplyfileimpl.cpp \
    network/access/qnetworkreplyhttpimpl.cpp \
    network/access/qnetworkreplyimpl.cpp \
    network/access/qnetworkreplywasmimpl.cpp \
    network/access/qnetworkrequest.cpp \
    network/access/qspdyprotocolhandler.cpp \
    network/bearer/qbearerengine.cpp \
    network/bearer/qbearerplugin.cpp \
    network/bearer/qnetworkconfigmanager.cpp \
    network/bearer/qnetworkconfigmanager_p.cpp \
    network/bearer/qnetworkconfiguration.cpp \
    network/bearer/qnetworksession.cpp \
    network/bearer/qsharednetworksession.cpp \
    network/doc/snippets/code/doc_src_qtnetwork.cpp \
    network/doc/snippets/code/src_network_access_qftp.cpp \
    network/doc/snippets/code/src_network_access_qhttpmultipart.cpp \
    network/doc/snippets/code/src_network_access_qhttppart.cpp \
    network/doc/snippets/code/src_network_access_qnetworkaccessmanager.cpp \
    network/doc/snippets/code/src_network_access_qnetworkdiskcache.cpp \
    network/doc/snippets/code/src_network_access_qnetworkreply.cpp \
    network/doc/snippets/code/src_network_access_qnetworkrequest.cpp \
    network/doc/snippets/code/src_network_bearer_qnetworkconfigmanager.cpp \
    network/doc/snippets/code/src_network_bearer_qnetworksession.cpp \
    network/doc/snippets/code/src_network_kernel_qdnslookup.cpp \
    network/doc/snippets/code/src_network_kernel_qhostaddress.cpp \
    network/doc/snippets/code/src_network_kernel_qhostinfo.cpp \
    network/doc/snippets/code/src_network_kernel_qnetworkdatagram.cpp \
    network/doc/snippets/code/src_network_kernel_qnetworkinterface.cpp \
    network/doc/snippets/code/src_network_kernel_qnetworkproxy.cpp \
    network/doc/snippets/code/src_network_socket_qabstractsocket.cpp \
    network/doc/snippets/code/src_network_socket_qlocalsocket_unix.cpp \
    network/doc/snippets/code/src_network_socket_qnativesocketengine.cpp \
    network/doc/snippets/code/src_network_socket_qsctpsocket.cpp \
    network/doc/snippets/code/src_network_socket_qtcpserver.cpp \
    network/doc/snippets/code/src_network_socket_qudpsocket.cpp \
    network/doc/snippets/code/src_network_ssl_qdtls.cpp \
    network/doc/snippets/code/src_network_ssl_qdtlscookie.cpp \
    network/doc/snippets/code/src_network_ssl_qsslcertificate.cpp \
    network/doc/snippets/code/src_network_ssl_qsslconfiguration.cpp \
    network/doc/snippets/code/src_network_ssl_qsslpresharedkeyauthenticator.cpp \
    network/doc/snippets/code/src_network_ssl_qsslsocket.cpp \
    network/doc/snippets/network/tcpwait.cpp \
    network/kernel/qauthenticator.cpp \
    network/kernel/qdnslookup.cpp \
    network/kernel/qdnslookup_android.cpp \
    network/kernel/qdnslookup_unix.cpp \
    network/kernel/qdnslookup_win.cpp \
    network/kernel/qdnslookup_winrt.cpp \
    network/kernel/qhostaddress.cpp \
    network/kernel/qhostinfo.cpp \
    network/kernel/qhostinfo_unix.cpp \
    network/kernel/qhostinfo_win.cpp \
    network/kernel/qnetworkdatagram.cpp \
    network/kernel/qnetworkinterface.cpp \
    network/kernel/qnetworkinterface_linux.cpp \
    network/kernel/qnetworkinterface_unix.cpp \
    network/kernel/qnetworkinterface_win.cpp \
    network/kernel/qnetworkinterface_winrt.cpp \
    network/kernel/qnetworkproxy.cpp \
    network/kernel/qnetworkproxy_generic.cpp \
    network/kernel/qnetworkproxy_libproxy.cpp \
    network/kernel/qnetworkproxy_mac.cpp \
    network/kernel/qnetworkproxy_win.cpp \
    network/kernel/qurlinfo.cpp \
    network/socket/qabstractsocket.cpp \
    network/socket/qabstractsocketengine.cpp \
    network/socket/qhttpsocketengine.cpp \
    network/socket/qlocalserver.cpp \
    network/socket/qlocalserver_tcp.cpp \
    network/socket/qlocalserver_unix.cpp \
    network/socket/qlocalserver_win.cpp \
    network/socket/qlocalsocket.cpp \
    network/socket/qlocalsocket_tcp.cpp \
    network/socket/qlocalsocket_unix.cpp \
    network/socket/qlocalsocket_win.cpp \
    network/socket/qnativesocketengine.cpp \
    network/socket/qnativesocketengine_unix.cpp \
    network/socket/qnativesocketengine_win.cpp \
    network/socket/qnativesocketengine_winrt.cpp \
    network/socket/qsctpserver.cpp \
    network/socket/qsctpsocket.cpp \
    network/socket/qsocks5socketengine.cpp \
    network/socket/qtcpserver.cpp \
    network/socket/qtcpsocket.cpp \
    network/socket/qudpsocket.cpp \
    network/ssl/qasn1element.cpp \
    network/ssl/qdtls.cpp \
    network/ssl/qdtls_openssl.cpp \
    network/ssl/qpassworddigestor.cpp \
    network/ssl/qssl.cpp \
    network/ssl/qsslcertificate.cpp \
    network/ssl/qsslcertificate_openssl.cpp \
    network/ssl/qsslcertificate_qt.cpp \
    network/ssl/qsslcertificate_winrt.cpp \
    network/ssl/qsslcertificateextension.cpp \
    network/ssl/qsslcipher.cpp \
    network/ssl/qsslconfiguration.cpp \
    network/ssl/qsslcontext_openssl.cpp \
    network/ssl/qsslcontext_openssl11.cpp \
    network/ssl/qsslcontext_opensslpre11.cpp \
    network/ssl/qssldiffiehellmanparameters.cpp \
    network/ssl/qssldiffiehellmanparameters_dummy.cpp \
    network/ssl/qssldiffiehellmanparameters_openssl.cpp \
    network/ssl/qsslellipticcurve.cpp \
    network/ssl/qsslellipticcurve_dummy.cpp \
    network/ssl/qsslellipticcurve_openssl.cpp \
    network/ssl/qsslerror.cpp \
    network/ssl/qsslkey_mac.cpp \
    network/ssl/qsslkey_openssl.cpp \
    network/ssl/qsslkey_p.cpp \
    network/ssl/qsslkey_qt.cpp \
    network/ssl/qsslkey_winrt.cpp \
    network/ssl/qsslpresharedkeyauthenticator.cpp \
    network/ssl/qsslsocket.cpp \
    network/ssl/qsslsocket_mac.cpp \
    network/ssl/qsslsocket_mac_shared.cpp \
    network/ssl/qsslsocket_openssl.cpp \
    network/ssl/qsslsocket_openssl11.cpp \
    network/ssl/qsslsocket_openssl_android.cpp \
    network/ssl/qsslsocket_openssl_symbols.cpp \
    network/ssl/qsslsocket_opensslpre11.cpp \
    network/ssl/qsslsocket_winrt.cpp \
    network/ssl/qwindowscarootfetcher.cpp \
    CopidQt/implement/qthread_unix.cpp

HEADERS += \
    CopidQt/Widget/qaction.h \
    CopidQt/Widget/qaction_p.h \
    CopidQt/Widget/qactiongroup.h \
    CopidQt/Widget/qapplication.h \
    CopidQt/Widget/qapplication_p.h \
    CopidQt/Widget/qboxlayout.h \
    CopidQt/Widget/qdesktopwidget.h \
    CopidQt/Widget/qdesktopwidget_p.h \
    CopidQt/Widget/qformlayout.h \
    CopidQt/Widget/qgesture.h \
    CopidQt/Widget/qgesture_p.h \
    CopidQt/Widget/qgesturemanager_p.h \
    CopidQt/Widget/qgesturerecognizer.h \
    CopidQt/Widget/qgridlayout.h \
    CopidQt/Widget/qlayout.h \
    CopidQt/Widget/qlayout_p.h \
    CopidQt/Widget/qlayoutengine_p.h \
    CopidQt/Widget/qlayoutitem.h \
    CopidQt/Widget/qmacgesturerecognizer_p.h \
    CopidQt/Widget/qopenglwidget.h \
    CopidQt/Widget/qshortcut.h \
    CopidQt/Widget/qsizepolicy.h \
    CopidQt/Widget/qstackedlayout.h \
    CopidQt/Widget/qstandardgestures_p.h \
    CopidQt/Widget/qt_widgets_pch.h \
    CopidQt/Widget/qtestsupport_widgets.h \
    CopidQt/Widget/qtooltip.h \
    CopidQt/Widget/qtwidgetsglobal.h \
    CopidQt/Widget/qtwidgetsglobal_p.h \
    CopidQt/Widget/qwhatsthis.h \
    CopidQt/Widget/qwidget.h \
    CopidQt/Widget/qwidget_p.h \
    CopidQt/Widget/qwidgetaction.h \
    CopidQt/Widget/qwidgetaction_p.h \
    CopidQt/Widget/qwidgetbackingstore_p.h \
    CopidQt/Widget/qwidgetwindow_p.h \
    CopidQt/Widget/qwindowcontainer_p.h \
    CopidQt/gui/kernel/qclipboard.h \
    CopidQt/gui/kernel/qcursor.h \
    CopidQt/gui/kernel/qcursor_p.h \
    CopidQt/gui/kernel/qdnd_p.h \
    CopidQt/gui/kernel/qdrag.h \
    CopidQt/gui/kernel/qevent.h \
    CopidQt/gui/kernel/qevent_p.h \
    CopidQt/gui/kernel/qgenericplugin.h \
    CopidQt/gui/kernel/qgenericpluginfactory.h \
    CopidQt/gui/kernel/qguiapplication.h \
    CopidQt/gui/kernel/qguiapplication_p.h \
    CopidQt/gui/kernel/qhighdpiscaling_p.h \
    CopidQt/gui/kernel/qinputdevicemanager_p.h \
    CopidQt/gui/kernel/qinputdevicemanager_p_p.h \
    CopidQt/gui/kernel/qinputmethod.h \
    CopidQt/gui/kernel/qinputmethod_p.h \
    CopidQt/gui/kernel/qinternalmimedata_p.h \
    CopidQt/gui/kernel/qkeymapper_p.h \
    CopidQt/gui/kernel/qkeysequence.h \
    CopidQt/gui/kernel/qkeysequence_p.h \
    CopidQt/gui/kernel/qoffscreensurface.h \
    CopidQt/gui/kernel/qopenglcontext.h \
    CopidQt/gui/kernel/qopenglcontext_p.h \
    CopidQt/gui/kernel/qopenglwindow.h \
    CopidQt/gui/kernel/qpaintdevicewindow.h \
    CopidQt/gui/kernel/qpaintdevicewindow_p.h \
    CopidQt/gui/kernel/qpalette.h \
    CopidQt/gui/kernel/qpixelformat.h \
    CopidQt/gui/kernel/qplatformclipboard.h \
    CopidQt/gui/kernel/qplatformcursor.h \
    CopidQt/gui/kernel/qplatformdialoghelper.h \
    CopidQt/gui/kernel/qplatformdrag.h \
    CopidQt/gui/kernel/qplatformgraphicsbuffer.h \
    CopidQt/gui/kernel/qplatformgraphicsbufferhelper.h \
    CopidQt/gui/kernel/qplatforminputcontext.h \
    CopidQt/gui/kernel/qplatforminputcontext_p.h \
    CopidQt/gui/kernel/qplatforminputcontextfactory_p.h \
    CopidQt/gui/kernel/qplatforminputcontextplugin_p.h \
    CopidQt/gui/kernel/qplatformintegration.h \
    CopidQt/gui/kernel/qplatformintegrationfactory_p.h \
    CopidQt/gui/kernel/qplatformintegrationplugin.h \
    CopidQt/gui/kernel/qplatformmenu.h \
    CopidQt/gui/kernel/qplatformnativeinterface.h \
    CopidQt/gui/kernel/qplatformoffscreensurface.h \
    CopidQt/gui/kernel/qplatformopenglcontext.h \
    CopidQt/gui/kernel/qplatformscreen.h \
    CopidQt/gui/kernel/qplatformscreen_p.h \
    CopidQt/gui/kernel/qplatformservices.h \
    CopidQt/gui/kernel/qplatformsessionmanager.h \
    CopidQt/gui/kernel/qplatformsharedgraphicscache.h \
    CopidQt/gui/kernel/qplatformsurface.h \
    CopidQt/gui/kernel/qplatformsystemtrayicon.h \
    CopidQt/gui/kernel/qplatformtheme.h \
    CopidQt/gui/kernel/qplatformtheme_p.h \
    CopidQt/gui/kernel/qplatformthemefactory_p.h \
    CopidQt/gui/kernel/qplatformthemeplugin.h \
    CopidQt/gui/kernel/qplatformwindow.h \
    CopidQt/gui/kernel/qplatformwindow_p.h \
    CopidQt/gui/kernel/qrasterwindow.h \
    CopidQt/gui/kernel/qscreen.h \
    CopidQt/gui/kernel/qscreen_p.h \
    CopidQt/gui/kernel/qsessionmanager.h \
    CopidQt/gui/kernel/qsessionmanager_p.h \
    CopidQt/gui/kernel/qshapedpixmapdndwindow_p.h \
    CopidQt/gui/kernel/qshortcutmap_p.h \
    CopidQt/gui/kernel/qsimpledrag_p.h \
    CopidQt/gui/kernel/qstylehints.h \
    CopidQt/gui/kernel/qsurface.h \
    CopidQt/gui/kernel/qsurfaceformat.h \
    CopidQt/gui/kernel/qt_gui_pch.h \
    CopidQt/gui/kernel/qtestsupport_gui.h \
    CopidQt/gui/kernel/qtguiglobal.h \
    CopidQt/gui/kernel/qtguiglobal_p.h \
    CopidQt/gui/kernel/qtouchdevice.h \
    CopidQt/gui/kernel/qtouchdevice_p.h \
    CopidQt/gui/kernel/qwindow.h \
    CopidQt/gui/kernel/qwindow_p.h \
    CopidQt/gui/kernel/qwindowdefs.h \
    CopidQt/gui/kernel/qwindowdefs_win.h \
    CopidQt/gui/kernel/qwindowsysteminterface.h \
    CopidQt/gui/kernel/qwindowsysteminterface_p.h \
    Core/qabstractanimation.h \
    Core/qabstracteventdispatcher.h \
    Core/qabstractitemmodel.h \
    Core/qabstractnativeeventfilter.h \
    Core/qabstractproxymodel.h \
    Core/qabstractstate.h \
    Core/qabstracttransition.h \
    Core/qalgorithms.h \
    Core/qanimationgroup.h \
    Core/qarraydata.h \
    Core/qarraydataops.h \
    Core/qarraydatapointer.h \
    Core/qatomic.h \
    Core/qatomic_bootstrap.h \
    Core/qatomic_cxx11.h \
    Core/qatomic_msvc.h \
    Core/qbasicatomic.h \
    Core/qbasictimer.h \
    Core/qbitarray.h \
    Core/qbuffer.h \
    Core/qbytearray.h \
    Core/qbytearraylist.h \
    Core/qbytearraymatcher.h \
    Core/qcache.h \
    Core/qcborarray.h \
    Core/qcborcommon.h \
    Core/qcbormap.h \
    Core/qcborstream.h \
    Core/qcborvalue.h \
    Core/qchar.h \
    Core/qcollator.h \
    Core/qcommandlineoption.h \
    Core/qcommandlineparser.h \
    Core/qcompilerdetection.h \
    Core/qconfig-bootstrapped.h \
    Core/qconfig.h \
    Core/qcontainerfwd.h \
    Core/qcontiguouscache.h \
    Core/qcoreapplication.h \
    Core/qcoreevent.h \
    Core/qcryptographichash.h \
    Core/qdatastream.h \
    Core/qdatetime.h \
    Core/qdeadlinetimer.h \
    Core/qdebug.h \
    Core/qdir.h \
    Core/qdiriterator.h \
    Core/qeasingcurve.h \
    Core/qelapsedtimer.h \
    Core/qendian.h \
    Core/qeventloop.h \
    Core/qeventtransition.h \
    Core/qexception.h \
    Core/qfactoryinterface.h \
    Core/qfile.h \
    Core/qfiledevice.h \
    Core/qfileinfo.h \
    Core/qfileselector.h \
    Core/qfilesystemwatcher.h \
    Core/qfinalstate.h \
    Core/qflags.h \
    Core/qfloat16.h \
    Core/qfunctions_nacl.h \
    Core/qfunctions_vxworks.h \
    Core/qfunctions_winrt.h \
    Core/qfuture.h \
    Core/qfutureinterface.h \
    Core/qfuturesynchronizer.h \
    Core/qfuturewatcher.h \
    Core/qgenericatomic.h \
    Core/qglobal.h \
    Core/qglobalstatic.h \
    Core/qhash.h \
    Core/qhashfunctions.h \
    Core/qhistorystate.h \
    Core/qidentityproxymodel.h \
    Core/qiodevice.h \
    Core/qisenum.h \
    Core/qitemselectionmodel.h \
    Core/qiterator.h \
    Core/qjsonarray.h \
    Core/qjsondocument.h \
    Core/qjsonobject.h \
    Core/qjsonvalue.h \
    Core/qlibrary.h \
    Core/qlibraryinfo.h \
    Core/qline.h \
    Core/qlinkedlist.h \
    Core/qlist.h \
    Core/qlocale.h \
    Core/qlockfile.h \
    Core/qlogging.h \
    Core/qloggingcategory.h \
    Core/qmap.h \
    Core/qmargins.h \
    Core/qmath.h \
    Core/qmessageauthenticationcode.h \
    Core/qmetaobject.h \
    Core/qmetatype.h \
    Core/qmimedata.h \
    Core/qmimedatabase.h \
    Core/qmimetype.h \
    Core/qmutex.h \
    Core/qnamespace.h \
    Core/qnumeric.h \
    Core/qobject.h \
    Core/qobject_impl.h \
    Core/qobjectcleanuphandler.h \
    Core/qobjectdefs.h \
    Core/qobjectdefs_impl.h \
    Core/qoperatingsystemversion.h \
    Core/qpair.h \
    Core/qparallelanimationgroup.h \
    Core/qpauseanimation.h \
    Core/qplugin.h \
    Core/qpluginloader.h \
    Core/qpoint.h \
    Core/qpointer.h \
    Core/qprocess.h \
    Core/qprocessordetection.h \
    Core/qpropertyanimation.h \
    Core/qqueue.h \
    Core/qrandom.h \
    Core/qreadwritelock.h \
    Core/qrect.h \
    Core/qrefcount.h \
    Core/qregexp.h \
    Core/qregularexpression.h \
    Core/qresource.h \
    Core/qresultstore.h \
    Core/qrunnable.h \
    Core/qsavefile.h \
    Core/qscopedpointer.h \
    Core/qscopedvaluerollback.h \
    Core/qscopeguard.h \
    Core/qsemaphore.h \
    Core/qsequentialanimationgroup.h \
    Core/qset.h \
    Core/qsettings.h \
    Core/qshareddata.h \
    Core/qsharedmemory.h \
    Core/qsharedpointer.h \
    Core/qsharedpointer_impl.h \
    Core/qsignalmapper.h \
    Core/qsignaltransition.h \
    Core/qsize.h \
    Core/qsocketnotifier.h \
    Core/qsortfilterproxymodel.h \
    Core/qstack.h \
    Core/qstandardpaths.h \
    Core/qstate.h \
    Core/qstatemachine.h \
    Core/qstorageinfo.h \
    Core/qstring.h \
    Core/qstringalgorithms.h \
    Core/qstringbuilder.h \
    Core/qstringlist.h \
    Core/qstringlistmodel.h \
    Core/qstringliteral.h \
    Core/qstringmatcher.h \
    Core/qstringview.h \
    Core/qsysinfo.h \
    Core/qsystemdetection.h \
    Core/qsystemsemaphore.h \
    Core/qt_windows.h \
    Core/qtcore-config.h \
    Core/qtcoreversion.h \
    Core/qtemporarydir.h \
    Core/qtemporaryfile.h \
    Core/qtestsupport_core.h \
    Core/qtextboundaryfinder.h \
    Core/qtextcodec.h \
    Core/qtextstream.h \
    Core/qthread.h \
    Core/qthreadpool.h \
    Core/qthreadstorage.h \
    Core/qtimeline.h \
    Core/qtimer.h \
    Core/qtimezone.h \
    Core/qtranslator.h \
    Core/qtypeinfo.h \
    Core/qtypetraits.h \
    Core/qurl.h \
    Core/qurlquery.h \
    Core/quuid.h \
    Core/qvariant.h \
    Core/qvariantanimation.h \
    Core/qvarlengtharray.h \
    Core/qvector.h \
    Core/qversionnumber.h \
    Core/qversiontagging.h \
    Core/qwaitcondition.h \
    Core/qwineventnotifier.h \
    Core/qxmlstream.h \
        mainwindow.h \
    mainwindow.h \
    CopidQt/header/qobject.h \
    mainwindow.h \
    CopidQt/implement/qabstracteventdispatcher.h \
    CopidQt/implement/qabstracteventdispatcher_p.h \
    CopidQt/implement/qabstractnativeeventfilter.h \
    CopidQt/implement/qbasictimer.h \
    CopidQt/implement/qcfsocketnotifier_p.h \
    CopidQt/implement/qcore_mac_p.h \
    CopidQt/implement/qcore_unix_p.h \
    CopidQt/implement/qcoreapplication.h \
    CopidQt/implement/qcoreapplication_p.h \
    CopidQt/implement/qcorecmdlineargs_p.h \
    CopidQt/implement/qcoreevent.h \
    CopidQt/implement/qcoreglobaldata_p.h \
    CopidQt/implement/qdeadlinetimer.h \
    CopidQt/implement/qdeadlinetimer_p.h \
    CopidQt/implement/qelapsedtimer.h \
    CopidQt/implement/qeventdispatcher_cf_p.h \
    CopidQt/implement/qeventdispatcher_glib_p.h \
    CopidQt/implement/qeventdispatcher_unix_p.h \
    CopidQt/implement/qeventdispatcher_win_p.h \
    CopidQt/implement/qeventdispatcher_winrt_p.h \
    CopidQt/implement/qeventloop.h \
    CopidQt/implement/qeventloop_p.h \
    CopidQt/implement/qfunctions_fake_env_p.h \
    CopidQt/implement/qfunctions_nacl.h \
    CopidQt/implement/qfunctions_p.h \
    CopidQt/implement/qfunctions_vxworks.h \
    CopidQt/implement/qfunctions_winrt.h \
    CopidQt/implement/qjni_p.h \
    CopidQt/implement/qjnihelpers_p.h \
    CopidQt/implement/qmath.h \
    CopidQt/implement/qmetaobject.h \
    CopidQt/implement/qmetaobject_moc_p.h \
    CopidQt/implement/qmetaobject_p.h \
    CopidQt/implement/qmetaobjectbuilder_p.h \
    CopidQt/implement/qmetatype.h \
    CopidQt/implement/qmetatype_p.h \
    CopidQt/implement/qmetatypeswitcher_p.h \
    CopidQt/implement/qmimedata.h \
    CopidQt/implement/qobject.h \
    CopidQt/implement/qobject_impl.h \
    CopidQt/implement/qobject_p.h \
    CopidQt/implement/qobjectcleanuphandler.h \
    CopidQt/implement/qobjectdefs.h \
    CopidQt/implement/qobjectdefs_impl.h \
    CopidQt/implement/qpointer.h \
    CopidQt/implement/qpoll_p.h \
    CopidQt/implement/qppsattribute_p.h \
    CopidQt/implement/qppsattributeprivate_p.h \
    CopidQt/implement/qppsobject_p.h \
    CopidQt/implement/qppsobjectprivate_p.h \
    CopidQt/implement/qsharedmemory.h \
    CopidQt/implement/qsharedmemory_p.h \
    CopidQt/implement/qsignalmapper.h \
    CopidQt/implement/qsocketnotifier.h \
    CopidQt/implement/qsystemerror_p.h \
    CopidQt/implement/qsystemsemaphore.h \
    CopidQt/implement/qsystemsemaphore_p.h \
    CopidQt/implement/qtimer.h \
    CopidQt/implement/qtimerinfo_unix_p.h \
    CopidQt/implement/qtranslator.h \
    CopidQt/implement/qtranslator_p.h \
    CopidQt/implement/qvariant.h \
    CopidQt/implement/qvariant_p.h \
    CopidQt/implement/qwineventnotifier.h \
    mainwindow.h \
    CopidQt/Widget/qabstractbutton.h \
    CopidQt/Widget/qabstractbutton_p.h \
    CopidQt/Widget/qabstractscrollarea.h \
    CopidQt/Widget/qabstractscrollarea_p.h \
    CopidQt/Widget/qabstractslider.h \
    CopidQt/Widget/qabstractslider_p.h \
    CopidQt/Widget/qabstractspinbox.h \
    CopidQt/Widget/qabstractspinbox_p.h \
    CopidQt/Widget/qaction.h \
    CopidQt/Widget/qaction_p.h \
    CopidQt/Widget/qactiongroup.h \
    CopidQt/Widget/qapplication.h \
    CopidQt/Widget/qapplication_p.h \
    CopidQt/Widget/qboxlayout.h \
    CopidQt/Widget/qbuttongroup.h \
    CopidQt/Widget/qbuttongroup_p.h \
    CopidQt/Widget/qcalendarwidget.h \
    CopidQt/Widget/qcheckbox.h \
    CopidQt/Widget/qcombobox.h \
    CopidQt/Widget/qcombobox_p.h \
    CopidQt/Widget/qcommandlinkbutton.h \
    CopidQt/Widget/qdatetimeedit.h \
    CopidQt/Widget/qdatetimeedit_p.h \
    CopidQt/Widget/qdesktopwidget.h \
    CopidQt/Widget/qdesktopwidget_p.h \
    CopidQt/Widget/qdial.h \
    CopidQt/Widget/qdialogbuttonbox.h \
    CopidQt/Widget/qdockarealayout_p.h \
    CopidQt/Widget/qdockwidget.h \
    CopidQt/Widget/qdockwidget_p.h \
    CopidQt/Widget/qeffects_p.h \
    CopidQt/Widget/qfocusframe.h \
    CopidQt/Widget/qfontcombobox.h \
    CopidQt/Widget/qformlayout.h \
    CopidQt/Widget/qframe.h \
    CopidQt/Widget/qframe_p.h \
    CopidQt/Widget/qgesture.h \
    CopidQt/Widget/qgesture_p.h \
    CopidQt/Widget/qgesturemanager_p.h \
    CopidQt/Widget/qgesturerecognizer.h \
    CopidQt/Widget/qgridlayout.h \
    CopidQt/Widget/qgroupbox.h \
    CopidQt/Widget/qkeysequenceedit.h \
    CopidQt/Widget/qkeysequenceedit_p.h \
    CopidQt/Widget/qlabel.h \
    CopidQt/Widget/qlabel_p.h \
    CopidQt/Widget/qlayout.h \
    CopidQt/Widget/qlayout_p.h \
    CopidQt/Widget/qlayoutengine_p.h \
    CopidQt/Widget/qlayoutitem.h \
    CopidQt/Widget/qlcdnumber.h \
    CopidQt/Widget/qlineedit.h \
    CopidQt/Widget/qlineedit_p.h \
    CopidQt/Widget/qmaccocoaviewcontainer_mac.h \
    CopidQt/Widget/qmacgesturerecognizer_p.h \
    CopidQt/Widget/qmacnativewidget_mac.h \
    CopidQt/Widget/qmainwindow.h \
    CopidQt/Widget/qmainwindowlayout_p.h \
    CopidQt/Widget/qmdiarea.h \
    CopidQt/Widget/qmdiarea_p.h \
    CopidQt/Widget/qmdisubwindow.h \
    CopidQt/Widget/qmdisubwindow_p.h \
    CopidQt/Widget/qmenu.h \
    CopidQt/Widget/qmenu_p.h \
    CopidQt/Widget/qmenubar.h \
    CopidQt/Widget/qmenubar_p.h \
    CopidQt/Widget/qopenglwidget.h \
    CopidQt/Widget/qplaintextedit.h \
    CopidQt/Widget/qplaintextedit_p.h \
    CopidQt/Widget/qprogressbar.h \
    CopidQt/Widget/qpushbutton.h \
    CopidQt/Widget/qpushbutton_p.h \
    CopidQt/Widget/qradiobutton.h \
    CopidQt/Widget/qrubberband.h \
    CopidQt/Widget/qscrollarea.h \
    CopidQt/Widget/qscrollarea_p.h \
    CopidQt/Widget/qscrollbar.h \
    CopidQt/Widget/qscrollbar_p.h \
    CopidQt/Widget/qshortcut.h \
    CopidQt/Widget/qsizegrip.h \
    CopidQt/Widget/qsizepolicy.h \
    CopidQt/Widget/qslider.h \
    CopidQt/Widget/qspinbox.h \
    CopidQt/Widget/qsplashscreen.h \
    CopidQt/Widget/qsplitter.h \
    CopidQt/Widget/qsplitter_p.h \
    CopidQt/Widget/qstackedlayout.h \
    CopidQt/Widget/qstackedwidget.h \
    CopidQt/Widget/qstandardgestures_p.h \
    CopidQt/Widget/qstatusbar.h \
    CopidQt/Widget/qt_widgets_pch.h \
    CopidQt/Widget/qtabbar.h \
    CopidQt/Widget/qtabbar_p.h \
    CopidQt/Widget/qtabwidget.h \
    CopidQt/Widget/qtestsupport_widgets.h \
    CopidQt/Widget/qtextbrowser.h \
    CopidQt/Widget/qtextedit.h \
    CopidQt/Widget/qtextedit_p.h \
    CopidQt/Widget/qtoolbar.h \
    CopidQt/Widget/qtoolbar_p.h \
    CopidQt/Widget/qtoolbararealayout_p.h \
    CopidQt/Widget/qtoolbarextension_p.h \
    CopidQt/Widget/qtoolbarlayout_p.h \
    CopidQt/Widget/qtoolbarseparator_p.h \
    CopidQt/Widget/qtoolbox.h \
    CopidQt/Widget/qtoolbutton.h \
    CopidQt/Widget/qtooltip.h \
    CopidQt/Widget/qtwidgetsglobal.h \
    CopidQt/Widget/qtwidgetsglobal_p.h \
    CopidQt/Widget/qwhatsthis.h \
    CopidQt/Widget/qwidget.h \
    CopidQt/Widget/qwidget_p.h \
    CopidQt/Widget/qwidgetaction.h \
    CopidQt/Widget/qwidgetaction_p.h \
    CopidQt/Widget/qwidgetanimator_p.h \
    CopidQt/Widget/qwidgetbackingstore_p.h \
    CopidQt/Widget/qwidgetlinecontrol_p.h \
    CopidQt/Widget/qwidgetresizehandler_p.h \
    CopidQt/Widget/qwidgettextcontrol_p.h \
    CopidQt/Widget/qwidgettextcontrol_p_p.h \
    CopidQt/Widget/qwidgetwindow_p.h \
    CopidQt/Widget/qwindowcontainer_p.h \
    network/access/http2/bitstreams_p.h \
    network/access/http2/hpack_p.h \
    network/access/http2/hpacktable_p.h \
    network/access/http2/http2frames_p.h \
    network/access/http2/http2protocol_p.h \
    network/access/http2/http2streams_p.h \
    network/access/http2/huffman_p.h \
    network/access/qabstractnetworkcache.h \
    network/access/qabstractnetworkcache_p.h \
    network/access/qabstractprotocolhandler_p.h \
    network/access/qftp_p.h \
    network/access/qhsts_p.h \
    network/access/qhstspolicy.h \
    network/access/qhstsstore_p.h \
    network/access/qhttp2protocolhandler_p.h \
    network/access/qhttpmultipart.h \
    network/access/qhttpmultipart_p.h \
    network/access/qhttpnetworkconnection_p.h \
    network/access/qhttpnetworkconnectionchannel_p.h \
    network/access/qhttpnetworkheader_p.h \
    network/access/qhttpnetworkreply_p.h \
    network/access/qhttpnetworkrequest_p.h \
    network/access/qhttpprotocolhandler_p.h \
    network/access/qhttpthreaddelegate_p.h \
    network/access/qnetworkaccessauthenticationmanager_p.h \
    network/access/qnetworkaccessbackend_p.h \
    network/access/qnetworkaccesscache_p.h \
    network/access/qnetworkaccesscachebackend_p.h \
    network/access/qnetworkaccessdebugpipebackend_p.h \
    network/access/qnetworkaccessfilebackend_p.h \
    network/access/qnetworkaccessftpbackend_p.h \
    network/access/qnetworkaccessmanager.h \
    network/access/qnetworkaccessmanager_p.h \
    network/access/qnetworkcookie.h \
    network/access/qnetworkcookie_p.h \
    network/access/qnetworkcookiejar.h \
    network/access/qnetworkcookiejar_p.h \
    network/access/qnetworkdiskcache.h \
    network/access/qnetworkdiskcache_p.h \
    network/access/qnetworkfile_p.h \
    network/access/qnetworkreply.h \
    network/access/qnetworkreply_p.h \
    network/access/qnetworkreplydataimpl_p.h \
    network/access/qnetworkreplyfileimpl_p.h \
    network/access/qnetworkreplyhttpimpl_p.h \
    network/access/qnetworkreplyimpl_p.h \
    network/access/qnetworkreplywasmimpl_p.h \
    network/access/qnetworkrequest.h \
    network/access/qnetworkrequest_p.h \
    network/access/qspdyprotocolhandler_p.h \
    network/bearer/qbearerengine_p.h \
    network/bearer/qbearerplugin_p.h \
    network/bearer/qnetworkconfigmanager.h \
    network/bearer/qnetworkconfigmanager_p.h \
    network/bearer/qnetworkconfiguration.h \
    network/bearer/qnetworkconfiguration_p.h \
    network/bearer/qnetworksession.h \
    network/bearer/qnetworksession_p.h \
    network/bearer/qsharednetworksession_p.h \
    network/kernel/qauthenticator.h \
    network/kernel/qauthenticator_p.h \
    network/kernel/qdnslookup.h \
    network/kernel/qdnslookup_p.h \
    network/kernel/qhostaddress.h \
    network/kernel/qhostaddress_p.h \
    network/kernel/qhostinfo.h \
    network/kernel/qhostinfo_p.h \
    network/kernel/qnetworkdatagram.h \
    network/kernel/qnetworkdatagram_p.h \
    network/kernel/qnetworkinterface.h \
    network/kernel/qnetworkinterface_p.h \
    network/kernel/qnetworkinterface_uikit_p.h \
    network/kernel/qnetworkinterface_unix_p.h \
    network/kernel/qnetworkproxy.h \
    network/kernel/qtnetworkglobal.h \
    network/kernel/qtnetworkglobal_p.h \
    network/kernel/qurlinfo_p.h \
    network/socket/qabstractsocket.h \
    network/socket/qabstractsocket_p.h \
    network/socket/qabstractsocketengine_p.h \
    network/socket/qhttpsocketengine_p.h \
    network/socket/qlocalserver.h \
    network/socket/qlocalserver_p.h \
    network/socket/qlocalsocket.h \
    network/socket/qlocalsocket_p.h \
    network/socket/qnativesocketengine_p.h \
    network/socket/qnativesocketengine_winrt_p.h \
    network/socket/qnet_unix_p.h \
    network/socket/qsctpserver.h \
    network/socket/qsctpserver_p.h \
    network/socket/qsctpsocket.h \
    network/socket/qsctpsocket_p.h \
    network/socket/qsocks5socketengine_p.h \
    network/socket/qtcpserver.h \
    network/socket/qtcpserver_p.h \
    network/socket/qtcpsocket.h \
    network/socket/qtcpsocket_p.h \
    network/socket/qudpsocket.h \
    network/ssl/qasn1element_p.h \
    network/ssl/qdtls.h \
    network/ssl/qdtls_openssl_p.h \
    network/ssl/qdtls_p.h \
    network/ssl/qpassworddigestor.h \
    network/ssl/qssl.h \
    network/ssl/qssl_p.h \
    network/ssl/qsslcertificate.h \
    network/ssl/qsslcertificate_p.h \
    network/ssl/qsslcertificateextension.h \
    network/ssl/qsslcertificateextension_p.h \
    network/ssl/qsslcipher.h \
    network/ssl/qsslcipher_p.h \
    network/ssl/qsslconfiguration.h \
    network/ssl/qsslconfiguration_p.h \
    network/ssl/qsslcontext_openssl_p.h \
    network/ssl/qssldiffiehellmanparameters.h \
    network/ssl/qssldiffiehellmanparameters_p.h \
    network/ssl/qsslellipticcurve.h \
    network/ssl/qsslerror.h \
    network/ssl/qsslkey.h \
    network/ssl/qsslkey_p.h \
    network/ssl/qsslpresharedkeyauthenticator.h \
    network/ssl/qsslpresharedkeyauthenticator_p.h \
    network/ssl/qsslsocket.h \
    network/ssl/qsslsocket_mac_p.h \
    network/ssl/qsslsocket_openssl11_symbols_p.h \
    network/ssl/qsslsocket_openssl_p.h \
    network/ssl/qsslsocket_openssl_symbols_p.h \
    network/ssl/qsslsocket_opensslpre11_symbols_p.h \
    network/ssl/qsslsocket_p.h \
    network/ssl/qsslsocket_winrt_p.h \
    network/ssl/qwindowscarootfetcher_p.h \
    CopidQt/implement/qthread_p.h

FORMS += \
        mainwindow.ui

DISTFILES += \
    CopidQt/gui/kernel/kernel.pri \
    network/access/access.pri \
    network/access/http2/http2.pri \
    network/bearer/bearer.pri \
    network/configure.json \
    network/configure.pri \
    network/doc/images/network-examples.png \
    network/doc/images/roaming-states.png \
    network/doc/images/tcpstream.png \
    network/doc/images/udppackets.png \
    network/doc/qtnetwork.qdocconf \
    network/doc/src/bearermanagement.qdoc \
    network/doc/src/examples.qdoc \
    network/doc/src/external-resources.qdoc \
    network/doc/src/network-programming.qdoc \
    network/doc/src/qtnetwork.qdoc \
    network/doc/src/ssl.qdoc \
    network/kernel/kernel.pri \
    network/socket/socket.pri \
    network/ssl/ssl.pri

SUBDIRS += \
    network/doc/snippets/code/doc_src_qtnetwork.pro \
    network/network.pro
