language: objective-c
osx_image: xcode11.2
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - IOS_SDK=iphonesimulator13.2
xcode_scheme: Debug
script:
  - xcodebuild -showsdks
  - xcodebuild -project Project/Vision.xcodeproj -scheme Debug -sdk $IOS_SDK build analyze
