# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

target 'NewsDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NewsDemo
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'HandyJSON'
  pod 'Kingfisher'
  pod 'IBAnimatable'
  pod 'SwiftTheme'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'SQLite.swift'
  pod 'SVProgressHUD'
  pod 'MJRefresh'
  pod 'SGPagingView'
  
end
