# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'rxDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for rxDemo
  pod "RxSwift"
  pod "RxCocoa"


  target 'rxDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'rxDemoUITests' do
    # Pods for testing
  end

end
